### ISSUE TITLE
No match in db, do not add to vcf file

### ISSUE THREAD

**Issue by henrikstranneheim** [J35P312/SVDB#11]
For instance, if a variant is not in the patogenic database - do not print that info to the vcf.

##INFO=<ID=clingen_cgh_pathogenic,Number=1,Type=Integer,Description="The number of occurances of the event in the database">

yields: clingen_cgh_pathogenic=0 in the INFO field. clingen_cgh_pathogenic=1 is informative 0 is not

**Comment by J35P312** [comment]
Thanks for the input, I fixed this a couple of commits ago! =P
