### ISSUE TITLE
Interpretation of genotype counts

### ISSUE THREAD

**Issue by holtgrewe** [J35P312/SVDB#14]
When importing the 1000 genomes data into a SQLite database and querying the DB, it appears that any match found is registered with a frequency of "1.0". I find this weird as the genotyping information is available and the frequency of the variant in the G1K cohort could be given.

Am I missing something?

**Comment by J35P312** [comment]
Hello there!
you can query the 1000 genomes vcf directly,  like this:

svdb --query --query_vcf /home/jesper/tiddit/NA12878_vcf/NA12878.before_change.vcf --db ALL.wgs.mergedSV.v8.20130502.svs.genotypes.vcf > test.out

or

svdb --query --query_vcf /home/jesper/tiddit/NA12878_vcf/NA12878.before_change.vcf --db ALL.wgs.mergedSV.v8.20130502.svs.genotypes.vcf --no_var --overlap 0.5 --bnd_distance 25000 > test.out

As of  now, the SVDB build step assumes that all input vcf files are single sample vcf files. So you will need to split the 1000 genomes vcf per individual to get the correct frequencies. I will fix this in the future, but for now you need to build you database from single sample vcf.

By the way, recently a database of 1000 swedish individuals was created, you could try it aswell in the same way:

https://swefreq.nbis.se/

Good luck!

**Comment by holtgrewe** [comment]
Thanks for the info
