### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by holtgrewe** [J35P312/SVDB#15]
Hi.

Would you accept a PR that makes the code work both with Python 2 and 3?

I'd also add a basic integration with Travis if you agree.

**Comment by J35P312** [comment]
Hello there!
Thanks for making the bioconda package!

It would be great if you have time! Both python 3 compability and travis integration would be nice and useful. The SVDB  code is a bit messy and in need of refactoring, which I hopefully will have time to do soon. But you are very welcome to dig in to the SVDB code if you dare ;P.

If you create a PR I will have look at it and accept it!
Have a nice weekend!
//Jesper

**Comment by J35P312** [comment]
Hello there, and sorry for the delay!
I have made SVDB python 3 compatible

**Comment by fgvieira** [comment]
I just tried installing it under python3 and got an error:
```
$ svdb --help
Traceback (most recent call last):
  File "/home/projects/cu_10047/people/filipev/.conda/envs/genmod/bin/svdb", line 6, in <module>
    from svdb.__main__ import main
  File "/home/projects/cu_10047/people/filipev/.conda/envs/genmod/lib/python3.7/site-packages/svdb/__main__.py", line 4, in <module>
    from . import query_module
  File "/home/projects/cu_10047/people/filipev/.conda/envs/genmod/lib/python3.7/site-packages/svdb/query_module.py", line 58
    print "##SVDB_version={} cmd=\"{}\"".format(args.version," ".join(sys.argv))
                                       ^
SyntaxError: invalid syntax
```

**Comment by J35P312** [comment]
Woopsie daisy!
Sorry, I forgot adding parenthesis to the query module!

Now it works in python 3.7:

svdb
usage: SVDB-2.1.1, use the build module to construct databases, use the query module to query the database usign vcf files, or use the hist module to generate histograms
       [--build] [--query] [--merge] [--export]

optional arguments:
  --build   create a db
  --query   query a db
  --merge   merge similar structural variants within a vcf file
  --export  export a database

**Comment by fgvieira** [comment]
Working fine now!
thanks,
