### ISSUE TITLE
Include all SV IDs on the merged ID

### ISSUE THREAD

**Issue by fgvieira** [J35P312/SVDB#19]
When merging SVs, would it be possible to add an option to set the SV's ID to the concatenation (or unique concatenation) of all the IDs collapsed (rather than the first ID)?

For example, if I am merging the SVs:
```
1	176478235	476	[...]
1	176478217	MantaDEL:13605:0:1:0:0:0	[...]
```

I'd get:
```
1	176478217	MantaDEL:13605:0:1:0:0:0;476	[...]
```

thanks

**Comment by J35P312** [comment]
Hello there and thanks for  your feedback!
I have updated SVDB; now the ID  of the  merged variant will both variant IDS of the separate variants as well as the filename of the files which they originate
