### ISSUE TITLE
Keep sample (genotype) information

### ISSUE THREAD

**Issue by fgvieira** [J35P312/SVDB#20]
When merging VCFs, would it be possible to keep the sample/genotype information? If nothing else, just the genotype (if they agree) or missing genotype (./.) if they don't.

thanks,

**Comment by J35P312** [comment]
Hello there!
And thanks for your feedback!
I will look into these issues next week!

Regards
//JEsper

**Comment by J35P312** [comment]
sample and  genotype information should be kept when merging using the  --merge command;
could you send example variants? I will have  a look at why the  genotype information is lost!
//Jespere

**Comment by fgvieira** [comment]
Humm, just tested it again, and now it seems ok.... maybe I was using some weird VCF.
Sorry about that.. :)
thanks,
