### ISSUE TITLE
Add option to only include PASS SVs when building DB

### ISSUE THREAD

**Issue by fgvieira** [J35P312/SVDB#24]
Hi,

would it be possible to have an option to only include SVs (e.g.) with `FILTER=PASS` when building the DB? Right now `svdb --build` uses all SVs, but sometimes it would be nice to have the option to only include the ones that `PASS`.
thanks,

**Comment by J35P312** [comment]
Hello!
Sorry for the delay!
I have now added such option:

svdb --build --folder /home/jesper/P1426/Delly/ --prefix DellyPASS --passonly

However, it adds variants with FILTER=Pass or FILTER=. (I have noticed that some callers do not set the filter for low quality calls); Feel free to try!
