### ISSUE TITLE
What do "filterIn" "FilteredInAll" and "Intersection" mean in set flag?

### ISSUE THREAD

**Issue by YiweiNiu** [J35P312/SVDB#26]

**Comment by J35P312** [comment]
Hello!
The SVDB set flag is similar to the GATK combine variants set flag ( https://gatkforums.broadinstitute.org/gatk/discussion/53/combining-variants-from-different-files-into-one  )

Intersection means the variant is found in all input files, and that the FILTER column is set to PASS for all of those variants

FilteredInAll means that the variant is found in all input files, and that the FILTER column is not set to pass in any of the variants.

Sometimes when merging files, a variant may be filtered by one caller, but not the other.
for instance:

set=Manta-FilterInDelly

here, the variant is labeled PASS by Manta, but not by Delly.

Have a look at the GATK link for more info, and feel free to ask if you have other questions!

**Comment by YiweiNiu** [comment]
Thank you very much!
