### ISSUE TITLE
Option to disable "Intersection" in set field

### ISSUE THREAD

**Issue by bjhall** [J35P312/SVDB#27]
When running SVDB --merge and the variant exists in all VCFs the INFO field "set" is set to "Intersection". 

This may be nice under some circumstances, but it would be great if this could be disabled with an option and just print all the names instead (like it does when fewer than all files intersect). 

For instance if you are merging files from 3 different variant callers, there is no way of knowing which callers were used when parsing the VCF, since set only says "Intersection".

Hope that makes sense.

**Comment by dnil** [comment]
It does indeed. This behaviour `(set=Intersection)` is modeled after what we get from GATK when merging calls from different SNV callers. If we could get them to change that would be great.

Note that e.g. Scout also supports a second format of noting multiple callers: `INFO.FOUND_IN`. A possibility could be to populate that field instead, but I can not speak for all downstream tools.

**Comment by bjhall** [comment]
Right, I forgot about the FOUND_IN format. I think I'm the reason it exists. :) I guess a temporary solution would be to add a step in our pipeline to convert "set" to "FOUND_IN".

The problem I'm trying to solve in the end is that, due to this, the list of variant callers needs to be hardcoded in Scout. And now we're setting up an inherited cancer panel which uses a different set of SV callers than our WGS pipeline. My idea was to fix the source of the problem rather than adding more hacks too scout... A hacky solution would be to add a list of variant callers to the case when loading it (in the yaml).

**Comment by dnil** [comment]
😄 Right! We just added a tacky hacky thing in scout with a fallback to GATK if there are no set= or FOUND_IN= but I don't like it. Something more general would be good, like a VCF header level element listing the possible set= elements for instance?

**Comment by bjhall** [comment]
Yes a VCF header entry would probably be the most reasonable solution!

**Comment by J35P312** [comment]
Hello there!
I hope to make an update to SVDB sometime next week!

I will make a command line option to do somehting like this then:

"This may be nice under some circumstances, but it would be great if this could be disabled with an option and just print all the names instead (like it does when fewer than all files intersect)."

Have  a nice weekend!
//JEsper
