### ISSUE TITLE
Query: Only write variants with frequency lower than a given value

### ISSUE THREAD

**Issue by DanielAndreasen** [J35P312/SVDB#31]
When quering an already existing DB with a new VCF, it would be nice to add an option to only include new variants and variants with a frequency below a given value, e.g. 5%. The default behaviour should of course be to include everything (new variants + variants of any frequency).
I have forked, implemented (not pushed yey) and tested this. It is quite simple to implement, but is it something you are interested in adopting if I make a pull request on it?

**Comment by J35P312** [comment]
Hello!
This sounds like a good idea, especially when having a very large and bulky database, which you do not want to make bigger.
Feel free to make a pull request!
//Jesper
