### ISSUE TITLE
What does the frequency mean?

### ISSUE THREAD

**Issue by DanielAndreasen** [J35P312/SVDB#33]
Hi Jesper,

I have a theoretical question about the frequency which comes out of SVDB.
Imagine I have 10 VCF files covering chr1 and chr2, with a similar variant in 3 of them (30% frequency) in chr1 at pos X, and another 90 VCF files **only** covering chr2.
All 100 VCF files are used to create a SVDB. What is the frequency from that SVDB in chr1 at pos X? Is it 30%, because only 3 out of possible 10 could catch this variant, or is it 3%, since 3 out of 100 have this variant?

**Comment by J35P312** [comment]
Hello!
SVDB does not check which chromosomes are analysed or not:
hence the frequency will be 3% (100 individuals, but only 3 carrying the SV). 

I will add this to the readme file!

As such, it is important not to for instance mix WES and WGS calls in the same database.
Have a nice weekend!
//jesper

**Comment by DanielAndreasen** [comment]
That is what I thought. Just wanted to be sure. Thanks for the swift reply.

Cheers,
Daniel
