### ISSUE TITLE
No_intra flag

### ISSUE THREAD

**Issue by Akazhiel** [J35P312/SVDB#42]
If we run the merge module without specifying the `--no_intra` flag. The variants that are merged within the same VCF, have to follow the same rules as the ones across VCFs? Meaning the variants have to be the same type and be withing a window?

Thanks in advance.

**Comment by J35P312** [comment]
Hello!
That is correct!
the variants within the same vcf are treated according to the same rules as those across other vcf files.
Good luck! //Jesper
