### ISSUE TITLE
How to combine delly,lumpy,manta and tiddit result?

### ISSUE THREAD

**Issue by ld9866** [J35P312/SVDB#60]
Dear developer:
Now we have used four methods to detect the structural variation of individuals, but we found that it can not well combined. We used the following code, but soon got an error report. How do you solve this problem?
svdb --merge --vcf ERS177302.delly.vcf ERS177302.lumpy.vcf ERS177302.manta.vcf ERS177302.tiddit.vcf > ERS177302.combine.vcf

Traceback (most recent call last):
  File "/home/ld/anaconda3/bin/svdb", line 33, in <module>
    sys.exit(load_entry_point('svdb', 'console_scripts', 'svdb')())
  File "/home/ld/Software/SVDB-2.6.4/svdb/__main__.py", line 187, in main
    merge_vcf_module.main(args)
  File "/home/ld/Software/SVDB-2.6.4/svdb/merge_vcf_module.py", line 171, in main
    chrA, posA, chrB, posB, event_type, INFO, FORMAT = readVCF.readVCFLine(line)
  File "svdb/readVCF.py", line 12, in svdb.readVCF.readVCFLine
IndexError: list index out of range

**Comment by ld9866** [comment]
We found when we add the delly result "ERS177302.delly.vcf" the error occurred.
Could SVDB solve the delly result?

**Comment by ld9866** [comment]
We found when we add the delly result "ERS177302.delly.vcf" the error occurred.
Could SVDB solve the delly result?

**Comment by J35P312** [comment]
Hello!
And thanks for the detailed information!

SVDB crashes on line 12, while reading the delly vcf:

File "svdb/readVCF.py", line 12, in svdb.readVCF.readVCFLine

here SVDB tries to access the position of the variant (column 2 in the vcf):

    posA = int(variation[1])

Column 2 is not present:

IndexError: list index out of range

Delly VCF files are usually fine, they should have all mandatory columns. Maybe the vcf is broken? Have you checked the last lines of it (using tail for instance). Or could it be that the vcf is compressed? I would double check that the file is not compressed, then I would run it through gatk ValidateVariants or similar. 

Good luck!

**Comment by ld9866** [comment]
Thank you for your prompt reply!
We found errors in this vcf. Some of the first and last lines did not start with #. After deletion, it runs perfectly.
thank you!
