### ISSUE TITLE
Annotate missing values as -1

### ISSUE THREAD

**Issue by fellen31** [J35P312/SVDB#71]
Hi, 

Currently it seems like only variants that match the database gets occurrence and frequency tags in the INFO column. I'd like to be able to use `bcftools view -i 'colorsdb_af < 0.5'` to filter out common variants, but then variants that are not in the database will not be included in the output VCF, since they don't have the `colorsdb_af` tag.

E.g.:

`
svdb --query --query_vcf results/svs/single_sample/HG002.Revio/HG002.Revio_severus.vcf.gz --db CoLoRSdb.CHM13.v1.1.0.pbsv.jasmine.vcf.gz --in_occ AN --out_occ colorsdb_an --in_frq AF --out_frq colorsdb_af|bcftools view -i 'colorsdb_af < 0.5'
`

results in the following 3 variants:

```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  HG002.Revio
chr16   507738  severus_INS26   N       ACGTTTCCCGTTTTCAGTATCATCTGCCCGTTCTGAGCCATTTGCTCTCTAGCCCTACCATACAGCTGTCATCCTAAGAGT       60      PASS     PRECISE;SVTYPE=INS;SVLEN=81;MAPQ=60;FOUND_IN=severus;colorsdb_an=2762;colorsdb_af=0.000724113   GT:GQ:VAF:hVAF:DR:DV    0/1:38:0.44:0.44,0,0:5:4
chr16   767798  severus_INS36   N       GGGGCACGTGGAGGGGTCGCGTGGAGGAGGGGCGCGTGGAGGGGGCGCGTGGAGGAGGAGGGGCGCATGGGGGGGTGTGGA       60      PASS     IMPRECISE;SVTYPE=INS;SVLEN=81;MAPQ=60;FOUND_IN=severus;colorsdb_an=2762;colorsdb_af=0.000724113 GT:GQ:VAF:hVAF:DR:DV    0/1:108:0.5:0.5,0,0:15:15
chr16   960535  severus_DEL11   N       <DEL>   60      PASS    PRECISE;SVTYPE=DEL;SVLEN=263;END=960798;STRANDS=+-;MAPQ=60;FOUND_IN=severus;colorsdb_an=2762;colorsdb_af=0.019551        GT:GQ:VAF:hVAF:DR:DV    0/1:273:0.3:0.3,0,0:31:13
```

while there are 52 even more "rare" variants that are not included in the output. 

One way to solve this would be to code missing variants as -1.

**Comment by J35P312** [comment]
Hello!
This looks like a cool analysis, I look forward to hearing more about the results :P. This is a bit of a philosophical issue. We should discuss it with Anders and the gang!

For now, I suggest you instead exclude variants with high frequency. This should work:

bcftools view -e 'colorsdb_af > 0.5'

**Comment by fellen31** [comment]
Thanks, wasn't aware that excluding variants worked 😊I do like seeing that a variant was annotated, but that the value was missing, rather than not having anything it all. 

How should I filter out all variants that were missing? Having to do  ```bcftools -e 'colorsdb_af > 1'```  is less intuitive to me than  ```bcftools -i 'colorsdb_af < 0```.

**Comment by dnil** [comment]
Im probably missing what step you are at, but for both initial hard filer to avoid computing on millons of wt variants, and any final fine tuning filters to take you down to a clinically plausible set you would always only exclude. The novel variants are potentially super important in rare disease, even if this means we invite some extra noise. 😊

**Comment by fellen31** [comment]
> Im probably missing what step you are at, but for both initial hard filer to avoid computing on millons of wt variants, and any final fine tuning filters to take you down to a clinically plausible set you would always only exclude. The novel variants are potentially super important in rare disease, even if this means we invite some extra noise. 😊
> 
> -1 or some other NaN analog might work, but in general, not setting the flag is the more correct option. You will find most frequency annotation tools operate this way. Leaving an entry in the VCF header noting the operation is good practice though!

Sorry Daniel, filter out was the wrong choice of words. I would like to retain only novel variants in this case. I could do this with `bcftools -e 'colorsdb_af > 1'`. That was not very intuitive to me, because I thought of the allele frequency in the database as 0, or missing. Is there another way? 

I was not aware that most frequency annotations tools do it that way.

**Comment by dnil** [comment]
Good, good. Still not entirely sure I follow (what is an AF>1?) but e.g. `bcftools -e 'colorsdb_af > 0'` should only exclude variants that have a frequency annotated (the statement is true), and similarly for SVDB annotations.

**Comment by fellen31** [comment]
> Good, good. Still not entirely sure I follow (what is an AF>1?) but e.g. `bcftools -e 'colorsdb_af > 0'` should only exclude variants that have a frequency annotated (the statement is true), and similarly for SVDB annotations.

Thanks, `bcftools -e 'colorsdb_af > 0'` makes my head click! 😄 I'll close this if not setting the flag is the more correct option, and is the usual practice!

**Comment by fellen31** [comment]
Not sure what I was on about with > 1 😅

**Comment by dnil** [comment]
> Not sure what I was on about with > 1 😅

count>1 perhaps..
