### ISSUE TITLE
version

### ISSUE THREAD

**Issue by henrikstranneheim** [J35P312/SVDB#8]
Is there a --version flag? I cannot find it in the CLI

**Comment by J35P312** [comment]
Not yet, I'll add such flag!

**Comment by J35P312** [comment]
Now I have added the flag, both to the header and to the command line output:
##fileformat=VCFv4.1
##source=MergeVCF
##SVDB_version=1.0.6 cmd="/usr/local/bin/svdb --merge --vcf SVDB.vcf P2109_183.clean.dedup.recal_FindSV.vcf"

command line:
usage: SVDB-1.0.6, use the build module to construct databases, use the query module to query the database usign vcf files, or use the hist module to generate histograms
       [--build] [--hist] [--query] [--purge] [--merge] [--export]
       [--bed_annotation]

optional arguments:
  --build           create a db
  --hist            generate histograms o the performance of a db
  --query           query a db
  --purge           remove entries from a database
  --merge           merge similar structural variants within a vcf file
  --export          export a database
  --bed_annotation  annotate a vcf file using information stored in a bed file

I will make a new release (1.0.6)

**Comment by henrikstranneheim** [comment]
Great! Closing!
