### ISSUE TITLE
svdb query error using decipher db 

### ISSUE THREAD

**Issue by henrikstranneheim** [J35P312/SVDB#9]
It does not seem like svdb query produces a frequency tag. Here is the command:
```
$svdb --query --bnd_distance 25000 --overlap 0.8 --hit_tag decipher --frequency_tag decipherAF --db /mnt/hds/proj/cust003/develop/mip_references/GRCh37_svdb_query_decipher_-v1.0.0-.vcf --query_vcf /scratch/$SLURM_JOB_ID/118_SV_vt_svdbq.vcf.0 > /scratch/$SLURM_JOB_ID/118_SV_vt_svdbq.vcf.1
```

Here is a line from the db:
```
1       23946   del_4   N       <DEL>   .       PASS    SVTYPE=DEL;END=88271;OCCURENCES=27;FREQUENCY=0.031952663        GT      0/1
```
Only tags that are generated are:
decipher=0;decipherAF=0
decipher=1;decipherAF=1

**Comment by henrikstranneheim** [comment]
I found the issue I should have specifed OCCURRENCE and FREQUENCY instead of used the default: OCC and FRQ with the tag flags.

However, you might consider standardizing the vcf INFO keys for OCC and FRQ to avoid these issues in the future.

**Comment by henrikstranneheim** [comment]
@J35P312 Could you consider rennaming the INFO fields in the decipher db to OCC adn FRQ?

**Comment by J35P312** [comment]
Hello!
The main problem is that SVDB extract the frequency and number of samples from the format fields for each sample. I will need to change that behavior so that the user can choose to extract the frequency of the info field instead.
